FIND_PROGRAM(SPHINX_EXECUTABLE NAMES sphinx-build
  HINTS $ENV{SPHINX_DIR}
  PATHS ${SPHINX_PATH}
  PATH_SUFFIXES bin
  DOC "Sphinx documentation generator"
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Sphinx DEFAULT_MSG
  SPHINX_EXECUTABLE
)

MARK_AS_ADVANCED(
  SPHINX_EXECUTABLE
)
