Module: dune-fem
Version: 2.8-git
Author: The Dune-Fem developer team
Maintainer: dune-fem@lists.dune-project.org
Description: A discretization module providing an implementation of mathematical abstractions to solve PDEs on parallel computers including local grid adaptivity, dynamic load balancing, and higher order discretization schemes
URL: https://gitlab.dune-project.org/dune-fem/dune-fem
Python-Requires: fenics-ufl==2019.1.0 dune-alugrid dune-istl dune-localfunctions
Depends: dune-grid (>= 2.8)
Suggests: dune-alugrid (>= 2.8) dune-istl (>= 2.8) dune-localfunctions (>= 2.8) dune-spgrid (>= 2.8) dune-polygongrid
Whitespace-Hook: Yes
