function v = load_dof_vector_binary(filename)
%function A = load_dof_vector(filename)
%
% load binary file, which represents a vector of double values,
% e.g. generated by Dune::MatlabHelper::saveDofVectorBinary. Two magic
% numbers are read (double and int) to check the compatibility of the
% binary file. If binary format does not match, the reading must be 
% modified in this file.
%
% format: 
% magic number "DDV" for Dune Dof Vector  
% magic numbers: int 111, double 111 for platform check
% number of entries
% for 0.. numer_of_entries-1 double v   
% "EOF" as marker of EOF

% Bernard Haasdonk 15.12.2006

  fid = fopen(filename,'r');
  % if standard reading is not the correct format for a given binary
  % file, activate the following:
  %fid = fopen(filename,'r','ieee-be');
  
  magicstr = char(fread(fid,3,'char'))';
  if ~isequal(magicstr,'DDV')
    error('read magicstr doe not indicate Dune Dof Vector!');
  end;
  
  magicint = fread(fid,1,'int');
  magicdouble = fread(fid,1,'double');
  
  if (magicint~=111) | (magicdouble~=111.0)
    error(['magic numbers not read correctly, change the binary format in' ...
	   ' this reading routine!']);
  end;
  
  nentries = fread(fid,1,'int');
  
  disp(['generating and reading vector with ',num2str(nentries),' entries.']);

  v = fread(fid,nentries,'double');

  eofstr = char(fread(fid,3,'char'))';
  if ~isequal(eofstr,'EOF')
    error('read eofstr does not indicate end of binary file!');
  end;

  
